### PR TITLE
Rename class from ofxJSONElement → ofxJSON

### PR DESCRIPTION
**Pull request by mattfelsen**
Alright, not sure if you or @bakercp are into this, but instead of `typedef`'ing ofxJSON, this PR changes the entire class name, and reverses the typedef to keep backward compatibility. It just seems cleaner to me and should be the "standard" for new projects using this addon.

In addition, I rename the files, update the examples, and make all `ofLog*()` calls use the "ofxJSON" module name, so that calls to `ofSetLogLevel("ofxJSON", OF_LOG_WHATEVER)` will work correctly. I tested with a new empty project and also the example_file_read_write and write project.

👍🏼 or 👎🏼 ?

### CODE REVIEW

**Comment by bakercp** [comment]
Seems reasonable to me. I'd suggest that we let it sit for a few days to see if anyone else has thoughts. Personally I don't use ofxJSONElement much, but instead just use the library directly.

**Comment by bakercp** [comment]
To clarify, I use this add-on extensively, just not the class itself.

**Comment by armadillu** [comment]
Seems good to me too. The filename change will annoy a few people as you have to update project files, but its not that bad, and code becomes much more readable.

**Comment by bakercp** [comment]
I suppose my thoughts are -- since `ofJson` is now in the core (officially after 0.10.0 and in master now), rather than change the name of this and have people change their projects, if they are in the mood to change their projects, perhaps they should just go ahead and change them to use ofJson.  After converting a bunch of my projects to ofJson, the syntax is very similar.  Anyway, at this point, for backward compatibility, I'd vote to just leave this the same.

**Pull request closed without merging**
